name: Keep my Duolingo streak

on:
  workflow_dispatch:
    inputs:
      lessons:
        description: 'Number of lessons to be completed'
        required: false
        default: 1
        type: number
      learningLanguage:
        description: 'Language to learn'
        required: false
        default: "ru"
        type: string

  schedule:
    - cron: '0 16 * * *'  # 12:00 PM EDT
    - cron: '0 22 * * *'  # 6:00 PM EDT
    - cron: '0 4 * * *'   # 12:00 AM EDT
    - cron: '0 10 * * *'  # 6:00 AM EDT

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ github.event.inputs.lessons || 1 }}
          LEARNING_LANGUAGE: ${{ github.event.inputs.learningLanguage || 'ru' }}
